### ISSUE TITLE
关于下载文件MD5

### ISSUE THREAD

**Issue by CMJNB** [dyang886/Game-Cheats-Manager#11]
发现搜索《Fallout 4》下载的辐射4修改器与官网下载的不一致：
官网下载地址：[https://archive.flingtrainer.com/files/Fallout%204%20v1.0-v1.10.26%20Plus%2020%20Trainer.rar](https://archive.flingtrainer.com/files/Fallout%204%20v1.0-v1.10.26%20Plus%2020%20Trainer.rar)
这是与源文件进行对比
![md5](https://github.com/dyang886/Game-Cheats-Manager/assets/53365071/70e40f09-dca3-41d3-a4c3-e68b50aae2a9)

**Comment by dyang886** [comment]
因为下载后为了删除背景音乐，所有老修改器内的 mid 音频文件已用 Resource Hacker 移除
