### ISSUE TITLE
能否加入修改器更新检测？

### ISSUE THREAD

**Issue by 840119580** [dyang886/Game-Cheats-Manager#17]
如题：
修改器更新的话，工具不会更新最新修改器，重新搜索也会提示已存在
例如最近的重装前哨：https://flingtrainer.com/trainer/outpost-infinity-siege-trainer/
修改器更新频繁，希望加入更新检测

**Comment by dyang886** [comment]
预计 2.0 正式版加入

**Comment by 840119580** [comment]
非常感谢回复，如果需要测试新功能，我非常愿意贡献一份力量
