### ISSUE TITLE
导入修改器功能没法找到本地exe文件

### ISSUE THREAD

**Issue by magicalkejia** [dyang886/Game-Cheats-Manager#18]
如图片所示，在桌面上有一个从官方下载的exe文件
![image](https://github.com/dyang886/Game-Cheats-Manager/assets/49331250/b77696ed-1898-4df6-a903-73605745a598)
点击导入切换到桌面后，没法找到这个文件
![image](https://github.com/dyang886/Game-Cheats-Manager/assets/49331250/81b2fc51-3e2f-45c2-b9e3-a6f5f2ca25ba)
但是直接将文件名输入路径可以成功导入并启动，说明问题在文件检索上
![image](https://github.com/dyang886/Game-Cheats-Manager/assets/49331250/ed254192-fe6e-4db1-8c38-d85b27c4f655)

**Comment by dyang886** [comment]
找到问题了，下个版本修复
