### ISSUE TITLE
使用bug

### ISSUE THREAD

**Issue by 2508207487** [dyang886/Game-Cheats-Manager#19]
![1](https://github.com/dyang886/Game-Cheats-Manager/assets/115985765/a4416cda-ad44-472c-a5f6-5565e3df93d0)
![2](https://github.com/dyang886/Game-Cheats-Manager/assets/115985765/90d14384-c408-4313-b50b-eeadf2d9dafa)
左边的修改器是1.8版本时搜索下载的，换成2.0以后搜索就这样的，搜不出来

**Comment by dyang886** [comment]
这是因为用的小黑盒api不知道怎么不好使了，2.0正式版中文搜索将大更新，到时候会准确很多，目前请先搜索英文关键词
