### ISSUE TITLE
使用 中文-简体 时自动机翻导致游戏名称几乎不可用

### ISSUE THREAD

**Issue by zhuhansan666** [dyang886/Game-Cheats-Manager#2]
建议给个选项选择是否自动机翻, 或同时显示原文和机翻, 否则可能导致游戏名称混淆或无效, 或者您可以仅对搜索提供机翻

或者, 您可以使用 Steam 的搜索推荐, API 如下:
`https://store.steampowered.com/search/suggest?term={搜索词}&cc={国家与地区代码, 如: CN, HK, US}&l={语言, 如: schinese, tchinese}`
> 注意: 您可能需要将 URL 编码; API 是我现抓出来的, 具体用法未知, 您可以自行尝试, 我不对 API 使用方法保障

望开发者能够改进软件, 携手创建美好开源生态环境

**Comment by zhuhansan666** [comment]
当然, 您可以直接使用现成的对照表然后转换为易处理的格式 (包括但不限于 JSON, XML)
如下是可用的对照表的示例:

`https://www.cnblogs.com/gname/p/13695887.html`
`https://zhuanlan.zhihu.com/p/300989521`

**Comment by zhuhansan666** [comment]
`https://dontstarve.fandom.com/zh/wiki/%E4%B8%AD%E8%8B%B1%E5%90%8D%E8%A9%9E%E5%B0%8D%E7%85%A7%E8%A1%A8?variant=zh-cn`

**Comment by dyang886** [comment]
感谢你的建议，以下是我的回复：

- 关于Steam api搜索：由于很多游戏在Steam上没有中文名，亲测很多都搜不到，体验比直接机翻更差，因此不考虑
- 关于对照表：现在游戏数量非常大并且在不断更新，创造一个完整可用的对照表并不容易，如果单凭我的话不可能完成。您提供的对照表示例均只有少量游戏翻译，达不到可用状态
- 您提议的搜索结果显示原英文游戏名已被采纳，将在下个版本更新

**Comment by zhuhansan666** [comment]
感谢开发者对建议的郑重考虑
