### ISSUE TITLE
Wemod更新至9.0版本后Wemod Pro解锁功能失效且导致Wemod无法启动

### ISSUE THREAD

**Issue by ArcS17** [dyang886/Game-Cheats-Manager#25]
![image](https://github.com/dyang886/Game-Cheats-Manager/assets/94548426/1d2abd98-5bb1-4d23-9f90-a3bbf38c4cb0)
2.0.0 beta3版本下运行Wemod Pro解锁功能后会导致Wemod 9.0.1无法正常启动, 表现为任务管理器中出现Wemod进程后显示挂起并立即消失;

![image](https://github.com/dyang886/Game-Cheats-Manager/assets/94548426/9ebd2f48-d0dc-4c0f-93fc-5c0c5ac30d8f)
Wemod大版本更新至9.0.1, 可能对该破解方式进行了防护请问作者是否会继续维护该功能.

**Comment by rudylhm** [comment]
我遇到了同样的问题

**Comment by ArcS17** [comment]
wemod更新9.0版本后似乎增添了SHA256对asar文件完整性进行验证, 在此之前的破解方法将失效

**Comment by dyang886** [comment]
> wemod更新9.0版本后似乎增添了SHA256对asar文件完整性进行验证, 在此之前的破解方法将失效

好像是的，asar 文件哪怕解压后原封不动打包回去WeMod就启动不了。目前我的方法是下载9.0前最新版(8.19)，并取消自动更新，那么破解照用。管理器2.0时会运用此逻辑

**Comment by dyang886** [comment]
2.1.0版本已彻底解决此问题
