### ISSUE TITLE
支援繁體搜尋

### ISSUE THREAD

**Issue by NeKoOuO** [dyang886/Game-Cheats-Manager#27]
目前搜只能用英文搜

**Comment by dyang886** [comment]
支持繁体搜索的前提是得有一个繁体中文游戏名数据库，目前我是没找到

**Comment by NeKoOuO** [comment]
Steamdb如何🤔

**Comment by dyang886** [comment]
不行的，steamdb用的是steam api，但是steam很多游戏名都是只有英文名的，之前用过此方案但不可行

**Comment by NeKoOuO** [comment]
opencc 如何 近似詞還可以搜到

**Comment by lclalalalala** [comment]
> 不行的，steamdb用的是steam api，但是steam很多游戏名都是只有英文名的，之前用过此方案但不可行

用ChatGPT翻译一遍可行？

**Comment by NeKoOuO** [comment]
Gpt太雞肋了 因為很多遊戲名簡中名跟繁中不一樣 增加個繁簡轉換就能暫時解決繁體搜不到的問題了
