### ISSUE TITLE
字体问题

### ISSUE THREAD

**Issue by alwaysfirst** [dyang886/Game-Cheats-Manager#28]
更新2.0.0.0后，Win 11 Pro简体中文版下，发现字体似乎在渲染上有问题，感觉不是很平滑，包括菜单上的文字和一开始出现的那个非盈利软件的提示。也许是我没有对应的字体？或是高DPI缩放的问题？

另外，可否把菜单上文字的字号放大一些？

**Comment by dyang886** [comment]
字体文件都是软件本身包括的（在assets文件夹内），高dpi缩放也是qt本身就是自动调节的，我3840x2160分辨率下150%缩放字体也是清晰的，不知道你那边什么效果，麻烦截个图

**Comment by alwaysfirst** [comment]
![屏幕截图 2024-05-27 234909](https://github.com/dyang886/Game-Cheats-Manager/assets/6400010/ea5dac25-ccda-4ef5-907e-91ed6a4b716e)

字体看看多了好像也能接受了 :-) 

个人感觉可能还是字号的问题，能不能放大字号，比如跟notepad的菜单文字一样大？
