### ISSUE TITLE
[BUG?] GCM 会不停更新《真三国无双7：猛将传》的作弊器，似乎版本判断出了问题

### ISSUE THREAD

**Issue by AnnAngela** [dyang886/Game-Cheats-Manager#36]
<details>
<summary>录制视频</summary>

https://github.com/dyang886/Game-Cheats-Manager/assets/9762652/f8f8ccbd-d414-434d-a839-4ac428bf805d

</details>

版本：2.0.0

**Comment by dyang886** [comment]
这是由于修改器文件检测出来的版本是 2024-03-20，而官网上显示的版本为 2024-03-21，导致一直在更新。这个属于个例且并非软件问题，我只能在下个版本中排除当前修改器的这个版本的自动更新。

**Comment by Eyion** [comment]
小程序的有吗？比如山海北荒卷

**Comment by dyang886** [comment]
2.1.0版本已解决
