### ISSUE TITLE
安装设置了修改器下载目录之后，磁盘损坏，重新安装无法变更之前的下载目录，无法打开工具

### ISSUE THREAD

**Issue by ljp190** [dyang886/Game-Cheats-Manager#37]
![image](https://github.com/dyang886/Game-Cheats-Manager/assets/41749016/1b7b96e3-f80a-41f1-8c69-7a1a95fc2df9)
最早是用的 I 盘，但是 I 盘坏掉了，没有这个盘
卸载后重新安装，依旧提示这个错   配置文件到底在哪儿啊

**Comment by dyang886** [comment]
在 “C:\Users\用户名\AppData\Roaming\GCM Settings\settings.json”，删掉它恢复默认设置，下个版本会考虑到这个问题

**Comment by dyang886** [comment]
2.1.0版本已解决
