### ISSUE TITLE
艾尔登法环修改器无法在管理器内自动或手动更新，打开仍是20240508的版本

### ISSUE THREAD

**Issue by favourate3** [dyang886/Game-Cheats-Manager#38]
![image](https://github.com/dyang886/Game-Cheats-Manager/assets/43308976/c27c40e1-827f-40c9-bc93-95239508684e)

**Comment by dyang886** [comment]
已找到问题，下个版本修复，目前可以手动删除后重新下载

**Comment by dyang886** [comment]
2.1.0版本已解决
