### ISSUE TITLE
Failed to execute script 'gamecheats'due to unhandled

### ISSUE THREAD

**Issue by jamexiansen** [dyang886/Game-Cheats-Manager#39]
![image](https://github.com/dyang886/Game-Cheats-Manager/assets/76086917/afdbbff3-9ada-4861-b96b-551f08bd0796)
有没有遇到过这个的   原有的 丢失  卸载完  冲击重新 安装后就出现这个了

**Comment by dyang886** [comment]
#37

**Comment by jamexiansen** [comment]
> #37  首先谢谢  我还专门找用户文件夹里的配置了没想到他改名了
