### ISSUE TITLE
高分辨率显示下的缩放问题

### ISSUE THREAD

**Issue by ibin7777** [dyang886/Game-Cheats-Manager#4]
<img width="537" alt="image" src="https://github.com/dyang886/Game-Cheats-Manager/assets/64576479/ca24c545-bcd8-499c-9154-520a622470cb">
2k显示下界面模糊，已尝试可通过修改兼容性dpi设置改善。不过4k及以上分辨率估计就会太小了。

**Comment by dyang886** [comment]
我用的就是4k屏，确实糊。虽然早意识到这个问题，但是如你所说，让软件兼容dpi缩放的话高分辨率下会非常小，如果重新调整各组件大小的话我怕低分辨率屏界面过大。所以暂时不知道如何解决，tkinter本身好像也没有个合适的设置。

**Comment by dyang886** [comment]
经研究找到办法了，下个版本更新！

**Comment by dyang886** [comment]
1.2.5 已修复
