### ISSUE TITLE
找不到下载作弊器的目录，软件会闪退

### ISSUE THREAD

**Issue by FuHengYa** [dyang886/Game-Cheats-Manager#40]
把文件夹目录删除，然后再向目录中下载作弊器，软件报错404然后闪退，能否自动新建目录或者提示需要重新选择目录

**Comment by dyang886** [comment]
每次下载都会检测下载目录是否存在，不存在的话会自动重新创建，所以不会出现此问题。404错误是由于下载服务器选择了中国导致部分修改器无法下载，请切换成国际
