### ISSUE TITLE
自定义wemod路径未找到

### ISSUE THREAD

**Issue by yegetables** [dyang886/Game-Cheats-Manager#42]
导入自定义wemod安装路径
![Clip_2024-07-29_11-33-25](https://github.com/user-attachments/assets/838b36d5-2515-4082-8d00-db1d6564438b)
因为要求这样命名匹配否则不会识别
希望可以选择exe文件来执行,因为一些原因不方便更改exe命名
举例:scoop 安装 wemod 
![Clip_2024-07-29_11-52-46](https://github.com/user-attachments/assets/e27c1c16-3d9d-40d1-bf22-255e2d1637da)
![image](https://github.com/user-attachments/assets/1d7d6936-f973-4899-afff-64f1b96a9f7b)

**Comment by dyang886** [comment]
不用更改exe文件名，你图中框选的正则表达式匹配的是WeMod版本文件夹，即.../scoop/apps/wemod/app-9.7.0，而你现在是.../scoop/apps/wemod/9.7.0。把9.7.0这个文件夹改成app-9.7.0就行（这是WeMod默认安装时的文件夹命名）
