### ISSUE TITLE
无法通过软件内启动修改器

### ISSUE THREAD

**Issue by hsiayuchih** [dyang886/Game-Cheats-Manager#43]
通过软件启动后会有如下报错。另外想问下，导入修改器后有个提示询问是否删除原文件，点是后会把运行文件直接删掉了，导致修改器无法正常启动，有些好奇这个功能是做什么用的
![QQ20240730-003302](https://github.com/user-attachments/assets/42cefc20-653b-4203-9b7a-a3506e6be56e)

**Comment by dyang886** [comment]
导入功能是用来导入风灵月影单exe修改器文件，不是WeMod。其原理仅仅是复制exe文件到右下角的修改器下载目录。删除原文件就是剪切效果。

**Comment by dyang886** [comment]
在“自定义WeMod”面板下有WeMod安装路径

**Comment by dyang886** [comment]
路径不对，正确路径下能看到“app-版本号”这种文件夹

**Comment by hsiayuchih** [comment]
> 路径不对，正确路径下能看到“app-版本号”这种文件夹

我的理解是选择好指定路径后，wemod就会安装在你所选择的路径下，但是实际上并没有，还是会默认安装在系统盘下。难道不是我理解的这样？那如果想正确安装在非默认路径下应该需要怎么操作呢？

**Comment by dyang886** [comment]
不是的，这个路径选择是定位你安装的WeMod的位置，不是用来更改安装位置的，要安装在非默认路径下只能手动移动整个WeMod程序文件夹

**Comment by hsiayuchih** [comment]
> 不是的，这个路径选择是定位你安装的WeMod的位置，不是用来更改安装位置的，要安装在非默认路径下只能手动移动整个WeMod程序文件夹

好的了解了，谢谢！不过好像和初版确实不太一样了，印象中之前的版本好像是可以安装在非默认路径下的？
