### ISSUE TITLE
[BUG]点击自定义wemod后闪退

### ISSUE THREAD

**Issue by LOCKDOWN083199** [dyang886/Game-Cheats-Manager#44]
软件版本：2.1.1
进行的操作：点击"自定义wemod"后，在路径栏粘贴地址时代入了双引号"后崩溃(形如："c:/xxxx)，此后依次进行了软件重开，系统重启，卸载重装，注册表清空的操作后，点击"自定义wemod"后仍然闪退。

视频：
https://github.com/user-attachments/assets/4eeadbd8-5c25-4da4-8a4f-b3cf0444ccfc

猜测问题定位：文件路径字符串异常处理

希望作者大大能看到😘

**Comment by dyang886** [comment]
重下2.1.1版本，现在应该彻底解决了 [2.1.1版本下载](https://github.com/dyang886/Game-Cheats-Manager/releases/tag/v2.1.1)

**Comment by LOCKDOWN083199** [comment]
牛的大佬
