### ISSUE TITLE
激活高级版后wemod快捷键设置功能异常

### ISSUE THREAD

**Issue by Patchoulides** [dyang886/Game-Cheats-Manager#45]
通过管理器激活官网安装v9.7,0版本wemod后，wemod各类游戏的自定义快捷键修改功能异常，无法正常检测按键输入，表现为随机选取一段时间前按下的按键、检测时间延长（3秒左右）并频繁绑定为鼠标移动

**Comment by dyang886** [comment]
我试了一下发现确实有这个问题，但是激活前和激活后都有此问题，所以这是WeMod本身问题，无法解决

**Comment by Patchoulides** [comment]
> 我试了一下发现确实有这个问题，但是激活前和激活后都有此问题，所以这是WeMod本身问题，无法解决

我自己尝试的时候也尝试了一下，完全卸载然后重新安装的wemod并没有这个问题，貌似是因为多次输入导致程序检测异常，但就算每次单独输入也会有很明显的延迟问题

**Comment by 1592363624** [comment]
> 我试了一下发现确实有这个问题，但是激活前和激活后都有此问题，所以这是WeMod本身问题，无法解决

没有吧  我试了一下 全新安装的快捷键可以正常编辑  但是解锁之后就不行了

**Comment by wadffh45-max** [comment]
安装了这个管理器，在搜索栏里面没找到已安装的 wemod 版本，我忘记了如何激活 wemod 的 pro 版，可以说一下吗
