### ISSUE TITLE
启动后一直在更新风灵月影数据库

### ISSUE THREAD

**Issue by Selaginexu** [dyang886/Game-Cheats-Manager#46]
启动后一直在更新风灵月影数据库，无法使用搜索，重启也没用
![1](https://github.com/user-attachments/assets/7d69088d-d257-435d-a57e-40abb08073bb)

**Comment by dyang886** [comment]
网络问题，可以浏览器手动访问风灵月影官网，访问不了的话数据库也将无法更新

**Comment by Selaginexu** [comment]
> 网络问题，可以浏览器手动访问风灵月影官网，访问不了的话数据库也将无法更新

**我浏览器可以打开，但程序还是无法更新，这个很奇怪**
![image](https://github.com/user-attachments/assets/89d2bca0-e129-463e-9e39-eb98ecf9eef8)
电脑网络接入的是移动网络，改为连接电信的手机热点，程序可以更新了
