### ISSUE TITLE
无法启动修改器

### ISSUE THREAD

**Issue by memgkong** [dyang886/Game-Cheats-Manager#47]
![image](https://github.com/user-attachments/assets/4774c7e6-8275-4898-9862-aa3dc5dbc539)
![image](https://github.com/user-attachments/assets/7cd5ac30-afc3-423f-b59f-4c646b10520d)

如题，修改器无法启动，无论是双击还是点击启动按钮都只会弹出确认管理员权限，之后不启动，任务管理器中也没用相关进程

**Comment by dyang886** [comment]
修改器文件名改英文

**Comment by memgkong** [comment]
> 修改器文件名改英文

好了，谢谢

**Comment by memgkong** [comment]
> 修改器文件名改英文

**Comment by memgkong** [comment]
> > 修改器文件名改英文

好了，谢谢
