### ISSUE TITLE
Game Cheats Manager.exe打开自动变成后台程序

### ISSUE THREAD

**Issue by zhihaoHappyeveryday** [dyang886/Game-Cheats-Manager#54]
作者您好::
Game Cheats Manager.exe打开自动变成后台程序, 看不到软件界面;
![image](https://github.com/user-attachments/assets/71c79e11-a7d8-4c16-bdd4-e1d3ab1ae680)

**Comment by dyang886** [comment]
不太清楚这是什么情况，你是第一个遇到此问题的人，我能给的建议只有重启电脑

**Comment by zhihaoHappyeveryday** [comment]
> 不太清楚这是什么情况，你是第一个遇到此问题的人，我能给的建议只有重启电脑

重启尝试过了, 还Google搜索过

**Comment by NeKoOuO** [comment]
https://github.com/dyang886/Game-Save-Manager/issues/19

**Comment by zhihaoHappyeveryday** [comment]
> [dyang886/Game-Save-Manager#19](https://github.com/dyang886/Game-Save-Manager/issues/19)

好的, thanks
