### ISSUE TITLE
无法使用修改器

### ISSUE THREAD

**Issue by ChenYone** [dyang886/Game-Cheats-Manager#55]
幽灵行动荒野的修改器没法用说找不到地址，启用管理员身份运行也不行。
![微信图片_20240915211212](https://github.com/user-attachments/assets/d037e8af-9d72-4d51-a008-bfd5c567d44d)
![微信图片_20240915211212](https://github.com/user-attachments/assets/027a0272-a526-4516-8c52-1c7f96d4362f)

**Comment by dyang886** [comment]
#52
