### ISSUE TITLE
激活WeMod专业版后无法打开WeMod 且之后也无法打开

### ISSUE THREAD

**Issue by AwaSubaruOfficial** [dyang886/Game-Cheats-Manager#56]
点击激活WeMod专业版后WeMod无法正常启动 但是任务管理器和提示栏显示WeMod已启动 这是重装系统后发生的事 之前用的时候没有 初步怀疑是麦咖啡的事

**Comment by AwaSubaruOfficial** [comment]
问题解决了 就是迈克菲的锅 删除迈克菲后正常运行

**Comment by HanHanZzzzzzz** [comment]
更新了 WeMod 9.10.5 后又复现了 无法启动WeMod的情况

**Comment by dyang886** [comment]
> 更新了 WeMod 9.10.5 后又复现了 无法启动WeMod的情况

请使用低于此版本的WeMod，最新可用版本下载：https://storage-cdn.wemod.com/app/releases/stable/WeMod-9.10.3.exe

**Comment by Bapid** [comment]
> 点击激活WeMod专业版后WeMod无法正常启动 但是任务管理器和提示栏显示WeMod已启动 这是重装系统后发生的事 之前用的时候没有 初步怀疑是麦咖啡的事

请问下麦咖啡是啥，我升到最新版本也不能启动wemod了
