### ISSUE TITLE
WeMod更新到9.10.5版本后，自定义为专业版后无法打开WeMod

### ISSUE THREAD

**Issue by Zeuswaed1937** [dyang886/Game-Cheats-Manager#57]
作者您好！
大约24年10月5日前后，WeMod更新了一个版本为9.10.5，之前为版本为9.10.3
出现点击激活WeMod专业版后，点击WeMod图标，会出现WeMod软件无法开启，或者开启后卡在加载窗口界面（此时窗口不显示任何东西，包括最小化和关闭按钮），无法进入WeMod的情况，进而无法使用
上述情况在这两个版本中均有出现

**Comment by dyang886** [comment]
#56

**Comment by YinxiuJin** [comment]
请问解决了吗

**Comment by TXDYSYZF** [comment]
有人可以分享一下9.10.3 wemod版本吗

**Comment by TXDYSYZF** [comment]
> #56
赞

**Comment by dyang886** [comment]
新版本已解决：[Game Cheats Manager v2.1.3 Release](https://github.com/dyang886/Game-Cheats-Manager/releases/tag/v2.1.3)

**Comment by TXDYSYZF** [comment]
大佬，请收下我的膝盖
