### ISSUE TITLE
关于一次搜索想下载多个结果时

### ISSUE THREAD

**Issue by cyb233** [dyang886/Game-Cheats-Manager#58]
有时想直接下载一个系列游戏的修改器时，由于目前只支持单个下载，且下载提示信息会覆盖搜索结果，所以每下载一次就要重新搜索，我认为将下载提示信息移出到其他位置，如额外窗口，使用体验上或许会更好

**Comment by dyang886** [comment]
目前的搜索下载逻辑已固定，要更改的话有很多需改变的地方。一般来讲不会一次下大量修改器，况且搜索不会花很长时间，而每次只能下载一个也保证了不会对目标网站请求过多
