### ISSUE TITLE
多語言

### ISSUE THREAD

**Issue by NeKoOuO** [dyang886/Game-Cheats-Manager#6]
作者UI語言有考慮做多語言嗎?
如果有我可以幫忙繁化

**Comment by dyang886** [comment]
可以的，麻烦了！

如何添加繁体中文 UI 语言：
1. 创建 locale\zh_TW\LC_MESSAGES\Game Cheats Manager.po
2. 可以先从 zh_CN 下的 .po 文件复制一份，编辑文件内 msgstr，注意不要修改任何 msgid
