### ISSUE TITLE
激活wemod专业版之后打开wemod就是黑的，相当于打不开

### ISSUE THREAD

**Issue by 1592363624** [dyang886/Game-Cheats-Manager#63]
![image](https://github.com/user-attachments/assets/dd7e1de6-2511-4f06-920f-b175aba7f8d1)
![image](https://github.com/user-attachments/assets/d9c0d651-be79-4b98-ad33-8eb6430bd4dc)

**Comment by dyang886** [comment]
管理器需更新至最新版

**Comment by 1592363624** [comment]
> 管理器需更新至最新版

应该是最新版本的  我是官网才下载安装的

**Comment by 1592363624** [comment]
OK  我我试试  忘记了管理器不能自动更新  如果不想写自动更新  感觉可以搞个提示跟新  检查下版本号 这个方便点

**Comment by 1592363624** [comment]
> 管理器需更新至最新版

OK  我我试试  忘记了管理器不能自动更新  如果不想写自动更新  感觉可以搞个提示跟新  检查下版本号 这个方便点

**Comment by dyang886** [comment]
这个已经是有的
