### ISSUE TITLE
[Bug]搜索功能

### ISSUE THREAD

**Issue by NeKoOuO** [dyang886/Game-Cheats-Manager#7]
如果關掉始終以英文顯示搜索結果 
用繁體搜索就會導致卡住的現象
英文搜索目前沒這個問題

**Comment by dyang886** [comment]
我这边用繁体搜没出现卡住，你是搜什么卡住的？

**Comment by NeKoOuO** [comment]
> 我这边用繁体搜没出现卡住，你是搜什么卡住的？
> 
> 注意软件使用小黑盒 api 进行游戏名匹配（用于翻译中文关键词到英文以进行搜索及展示翻译后的搜索结果），由于小黑盒 api 只提供了简体中文游戏名，故以繁体中文展示搜索结果暂时不能实现

目前沒問題了
