### ISSUE TITLE
[Feature]雙語顯示

### ISSUE THREAD

**Issue by NeKoOuO** [dyang886/Game-Cheats-Manager#8]
增加搜尋結果顯示遊戲原文名的選項
如果只顯示翻譯語言  有時候在原文名認知度比較高的時候 會導致看翻譯名認不出什麼遊戲的問題
用雙語就可以互補 在找遊戲名認遊戲的時候 可以比較清楚

**Comment by dyang886** [comment]
因为已经有“始终以英文展示搜索结果”选项，因此不考虑同时展示翻译语言及原语言（英语）
